export const state = {
  isLoggedIn: false,
  player: {
    username: "",
    id: null,
  },
  game: {
    worldSize: 9600,
    onMobile: window.matchMedia("(pointer: coarse)").matches,
    onGamepad: false,
    started: false,
    packetNow: 0,
    player: {
      name: "PiGuy141",
      id: 1,
      x: 0,
      y: 0,
      prevX: 0,
      prevY: 0,
      hp: 0, 
      maxHp: 0,
      rotation: 0,
      score: 0,
      level: 1,
      lastShoot: 0,
      upgrades: 0,
    },
    stats: {
      regen: 0,
      maxHealth: 0,
      bulletSpeed: 0,
      bodyDamage: 0,
      bulletPenetration: 0,
      bulletDamage: 0,
      reload: 0,
      movementSpeed: 0,
    },
    polygons: [],
    bullets: [],
  },
};
